CibleWebForms/Controllers/AvancesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CibleWebForms.Models;

namespace CibleWebForms.Controllers
{
    public class AvancesController : Controller
    {
        private CibleRhWebAppEntities db = new CibleRhWebAppEntities();
        private Employe employe;

        // GET: Avances
        public async Task<ActionResult> Index()
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            var avances = db.Avances.Include(a => a.Employe).Include(a => a.RespExploitation).Include(a => a.RespPortefeuille).Include(a => a.Directeur);
            return View(await avances.ToListAsync());
        }

        // GET: Avances/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avance avance = await db.Avances.FindAsync(id);
            if (avance == null)
            {
                return HttpNotFound();
            }
            return View(avance);
        }

        // GET: Avances/Create
        public ActionResult Create()
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            ViewBag.IdEmploye = new SelectList(db.Employes, "IdEmploye", "Matricule");
            ViewBag.IdRE = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom");
            ViewBag.IdRP = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom");
            ViewBag.IdDIR = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom");
            return View();
        }

        // POST: Avances/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "IdRequete,CodeRequete,IdEmploye,Montant,Pourcentage,DelaiEnMois,MotifRequete,DateRequete,Statut,MotifAnnulation,MotifRejet,IdRP,TraitementRP,DateTraitementRP,IdRE,TraitementRE,DateTraitementRE,IdDIR,TraitementDIR,DateTraitementDIR,Comptabilise,AvanceEnvoyee")] Avance avance)
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            if (ModelState.IsValid)
            {
                db.Avances.Add(avance);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.IdEmploye = new SelectList(db.Employes, "IdEmploye", "Matricule", avance.IdEmploye);
            ViewBag.IdRE = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdRE);
            ViewBag.IdRP = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdRP);
            ViewBag.IdDIR = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdDIR);
            return View(avance);
        }

        // GET: Avances/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avance avance = await db.Avances.FindAsync(id);
            if (avance == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdEmploye = new SelectList(db.Employes, "IdEmploye", "Matricule", avance.IdEmploye);
            ViewBag.IdRE = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdRE);
            ViewBag.IdRP = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdRP);
            ViewBag.IdDIR = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdDIR);
            return View(avance);
        }

        // POST: Avances/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "IdRequete,CodeRequete,IdEmploye,Montant,Pourcentage,DelaiEnMois,MotifRequete,DateRequete,Statut,MotifAnnulation,MotifRejet,IdRP,TraitementRP,DateTraitementRP,IdRE,TraitementRE,DateTraitementRE,IdDIR,TraitementDIR,DateTraitementDIR,Comptabilise,AvanceEnvoyee")] Avance avance)
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            if (ModelState.IsValid)
            {
                db.Entry(avance).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IdEmploye = new SelectList(db.Employes, "IdEmploye", "Matricule", avance.IdEmploye);
            ViewBag.IdRE = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdRE);
            ViewBag.IdRP = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdRP);
            ViewBag.IdDIR = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdDIR);
            return View(avance);
        }

        // GET: Avances/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avance avance = await db.Avances.FindAsync(id);
            if (avance == null)
            {
                return HttpNotFound();
            }
            return View(avance);
        }

        // POST: Avances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            Avance avance = await db.Avances.FindAsync(id);
            db.Avances.Remove(avance);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }




        #region Modifications Personnelles




        // GET: Avances/Create
        [AllowAnonymous]
        public ActionResult DemanderAvance()
        {
            ViewBag.IdEmploye = new SelectList(db.Employes, "IdEmploye", "Matricule");
            ViewBag.IdRE = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom");
            ViewBag.IdRP = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom");
            ViewBag.IdDIR = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom");
            return View();
        }

        // POST: Avances/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DemanderAvance([Bind(Include = "Pourcentage,DelaiEnMois,MotifRequete")] Avance avance)
        {
            if(EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            if (ModelState.IsValid)
            {
                avance.IdEmploye = EmployesController.localEmploye.IdEmploye;
                avance.CodeRequete = Helpers.AvanceHelper.GenerateCodeAvance(EmployesController.localEmploye.Matricule);
                avance.DateRequete = DateTime.Now;
                avance.Statut = AppConstants.AvanceStatuts.REQUETEENATTENTE;
                avance.Comptabilise = false;
                avance.AvanceEnvoyee = false;
                db.Avances.Add(avance);
                await db.SaveChangesAsync();
                return RedirectToAction("Index","Navigation");
            }

            ViewBag.IdEmploye = new SelectList(db.Employes, "IdEmploye", "Matricule", avance.IdEmploye);
            ViewBag.IdRE = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdRE);
            ViewBag.IdRP = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdRP);
            ViewBag.IdDIR = new SelectList(db.Utilisateurs, "IdUtilisateur", "Prenom", avance.IdDIR);
            return View(avance);
        }







        #endregion


    }
}

CibleWebForms/Views/SharedConnected/_LayoutConnected.cshtml
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title - TABERNACLE</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/admin-lte/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/admin-lte/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    @*<link rel="stylesheet" href="dist/css/AdminLTE.min.css">*@
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect. -->
    @*<link rel="stylesheet" href="dist/css/skins/skin-blue.min.css">*@
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-blue sidebar-mini " id="mainBody">
    <div class="wrapper" >
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><p>CIBLE RH</p></span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" id="mainBodyToggle" class="sidebar-toggle" data-toggle="push-menu" role="button">
                </a>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="sidebar main-sidebar toggled" id="sidebarMenu">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar" >
                <!-- Sidebar Menu -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li>@Html.ActionLink("Acceuil", "Index", "Navigation")</li>
                    <li>@Html.ActionLink("Demander Avance", "DemanderAvance", "Avances")</li>
                    <li>@Html.ActionLink("Deconnexion", "Deconnexion", "Navigation")</li>
                </ul>
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content container-fluid">
                @RenderBody()
                <!--------------------------
                  | Your Page Content Here |
                  -------------------------->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="pull-right hidden-xs">
                By Cyberix
            </div>
            <!-- Default to the left -->
            <p>&copy; @DateTime.Now.Year - TABERNACLE</p>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 3 -->
    @*<script src="bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="dist/js/adminlte.min.js"></script>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/admin-lte/js")
    <script>
        $("#mainBodyToggle").click(function () {
            //alert("OK okok");
            var body = document.getElementById("mainBody");
            var sidebar = document.getElementById("sidebarMenu");

            if (body.classList.contains("sidebar-collapse") | sidebar.classList.contains("toggled")) {
                body.classList.remove("sidebar-collapse");
                body.classList.add("sidebar-open");
                sidebar.classList.remove("toggled"); 
            }
            else
            {
                body.classList.add("sidebar-collapse");
                body.classList.remove("sidebar-open");
                sidebar.classList.add("toggled");
            }

        });

    </script>
    @RenderSection("scripts", required: false)
    <!-- Optionally, you can add Slimscroll and FastClick plugins.
         Both of these plugins are recommended to enhance the
         user experience. -->
</body>
</html>