CibleWebForms/Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CibleWebForms.Models;
using System.Web.Security;

namespace CibleWebForms.Controllers
{
    public class NavigationController : Controller
    {
        private CibleRhWebAppEntities db = new CibleRhWebAppEntities();


        // GET: Avances
        public async Task<ActionResult> Index()
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            var avances = db.Avances.Where(a => a.IdEmploye == EmployesController.localEmploye.IdEmploye).Include(a => a.Employe).Include(a => a.RespExploitation).Include(a => a.RespPortefeuille).Include(a => a.Directeur);
            return View(await avances.ToListAsync());
        }

        // GET: Navigation/Details/5
        public async Task<ActionResult> Details(string CodeRequete)
        {
            if (EmployesController.localEmploye == null)
                return RedirectToAction("Connexion", "Employes");
            if (CodeRequete == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Avance avance = await db.Avances.FindAsync(CodeRequete);
            if (avance == null)
            {
                return HttpNotFound();
            }
            return View(avance);
        }
        [AllowAnonymous]
        public ActionResult Deconnexion()
        {
            EmployesController.localEmploye = null;
            FormsAuthentication.SignOut();
            return RedirectToAction("Connexion", "Employes");
        }
    }
}

CibleWebForms/Views/Navigation/Delete.cshtml
@model CibleWebForms.Models.Avance

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Avance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CodeRequete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodeRequete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Montant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Montant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pourcentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pourcentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DelaiEnMois)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DelaiEnMois)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotifRequete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotifRequete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateRequete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateRequete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotifAnnulation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotifAnnulation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotifRejet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotifRejet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TraitementRP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TraitementRP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTraitementRP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTraitementRP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TraitementRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TraitementRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTraitementRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTraitementRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TraitementDIR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TraitementDIR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTraitementDIR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTraitementDIR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comptabilise)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comptabilise)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvanceEnvoyee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvanceEnvoyee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employe.Matricule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employe.Matricule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RespExploitation.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RespExploitation.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RespPortefeuille.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RespPortefeuille.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Directeur.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Directeur.Prenom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CibleWebForms/Views/Navigation/Details.cshtml
@model CibleWebForms.Models.Avance

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Avance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CodeRequete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodeRequete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Montant)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Montant)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pourcentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pourcentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DelaiEnMois)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DelaiEnMois)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotifRequete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotifRequete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateRequete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateRequete)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Statut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Statut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotifAnnulation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotifAnnulation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotifRejet)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotifRejet)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TraitementRP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TraitementRP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTraitementRP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTraitementRP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TraitementRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TraitementRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTraitementRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTraitementRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TraitementDIR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TraitementDIR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateTraitementDIR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateTraitementDIR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comptabilise)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comptabilise)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvanceEnvoyee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvanceEnvoyee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Employe.Matricule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employe.Matricule)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RespExploitation.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RespExploitation.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RespPortefeuille.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RespPortefeuille.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Directeur.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Directeur.Prenom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdRequete }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CibleWebForms/Views/Navigation/Index.cshtml
@model IEnumerable<CibleWebForms.Models.Avance>

@{

    Layout = "~/Views/SharedConnected/_LayoutConnected.cshtml";
    ViewBag.Title = "DashBoard";
    
}

<h2>Liste Avances</h2>



<div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CodeRequete)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pourcentage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateRequete)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MotifRejet)
            </th>
            <th></th>
        </tr>
        </thead>
        <tfoot>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CodeRequete)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pourcentage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateRequete)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Statut)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MotifRejet)
                </th>
                <th></th>
            </tr>
        </tfoot>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CodeRequete)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pourcentage)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateRequete)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Statut)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MotifRejet)
                    </td>
                    <td>
                        @*@Html.ActionLink("Details", "Details","Navigation", new { CodeRequete = item.CodeRequete }) |
                        @Html.ActionLink("Supprimer", "Delete", "Navigation",  new { CodeRequete = item.CodeRequete })*@
                    </td>
                </tr>
            }

</table>
</div>