TabernacleManager/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TabernacleManager.Helpers;
using TabernacleManager.Models;

namespace TabernacleManager.Controllers
{
    [Authorize]
    public class ManagerController : Controller
    {
        
        public ActionResult Index()
        {
            ;
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                var user = TabernacleManagerViewHelper.GetTmView(HttpContext.User.Identity.Name);
                return View(user);
            }else
                return View();
        }
        
        public ActionResult AvanceDetails(string CodeRequete)
        {
            var user = TabernacleManagerViewHelper.GetTmViewByAvanceId(HttpContext.User.Identity.Name, CodeRequete);
            return View(user);
        }

        // GET: Avances/Delete/5
        public ActionResult RejetterAvance(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            if (!TabernacleManagerViewHelper.RejecterAvanceById(id, HttpContext.User.Identity.Name))
            {
                return HttpNotFound();
            }

            return RedirectToAction("Index");
        }

        
        public ActionResult AvancesByStatus(string statut)
        {
            ;
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                var user = TabernacleManagerViewHelper.GetTmViewByAvanceStatut(HttpContext.User.Identity.Name,statut);
                return View(user);
            }
            else
                return HttpNotFound();
        }

        public ActionResult ValiderAvance(int idAvance)
        {
            ;
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                var user = TabernacleManagerViewHelper.ValierAvanceById(HttpContext.User.Identity.Name, idAvance);
                return View(user);
            }
            else
                return HttpNotFound();
        }
    }
}

TabernacleManager/Views/Shared/_Layout.cshtml
@model TabernacleManager.Models.TabernacleManagerView

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin Panel</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/dist/css/skins/skin-blue.min.css">
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>C</b>-RH</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>TABERNACLE</b></span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="~/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                @if (Model == null)
                                {
                                    <span class="hidden-xs">Not Transmited</span>
                                }
                                else
                                {
                                    <span class="hidden-xs">@Html.Label(Model.Utilisateur.Nom + " " + Model.Utilisateur.Prenom)</span>
                                }
</a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="~/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                                    @if (Model == null)
                                    {
                                        <p>
                                            Not Transmited
                                            <small hidden>Member since Nov. 2012</small>
                                        </p>
                                    }
                                    else
                                    {
                                        <p>@Html.Label(Model.Utilisateur.Nom + " " + Model.Utilisateur.Prenom + " - " + Model.Utilisateur.Habilitation)</p>
                                    }
                                    
                                    
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            @if (!Model.Utilisateur.EstAdmin)
                                            {
                                                <a href="#" hidden>Compte</a>
                                            }
                                            else
                                            {
                                                <span>Administrateur</span>
                                            }
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div hidden class="pull-left">
                                        @Html.ActionLink("Profil", "LogOff", "Manager", null, new { @class = "btn btn-info" })
                                    </div>
                                    <div class="pull-right">
                                        @Html.ActionLink("Deconnexion", "LogOff", "Account", null, new { @class = "btn btn-danger" })
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        @if (Model == null)
                        {
                            <p>Not Transmited</p>
                        }
                        else
                        {
                            <p>@Html.Label(Model.Utilisateur.Nom + " " + Model.Utilisateur.Prenom)</p>
                        }
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Connecte</a>
                    </div><br/><br/><br/>
                </div>
                <!-- Sidebar Menu -->
                @Html.Partial("_MainMenu")
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong hidden>Copyright &copy; 2018 <a href="https://codinginfinite.com">CodingInfinite</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 3 -->
    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
</body>
</html>

TabernacleManager/Views/Shared/_MainMenu.cshtml
@model TabernacleManager.Models.TabernacleManagerView

@if (Model == null)
{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">HEADER</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="active"><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Link</span></a></li>
        <li><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
        <li class="treeview">
            <a href="@Url.Action("Index", "Manager")">
                <i class="fa fa-link"></i> <span>Multilevel</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("Index", "Manager")">Link in level 2</a></li>
                <li><a href="@Url.Action("Index", "Manager")">Link in level 2</a></li>
            </ul>
        </li>
    </ul>
}
else if (Model.Utilisateur.Habilitation == "PAIE" | Model.Utilisateur.Habilitation == "COMPTABILITE")
{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Menu De Navigation</li>
        <!-- Optionally, you can add icons to the links -->
        <li class="active"><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Consultation</span></a></li>
    </ul>
}
else if (Model.Utilisateur.Habilitation == "RESPONSABLE PORTEFEUILLE")
{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Menu De Navigation</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Consultation</span></a></li>
        <li><a href="@Url.Action("AvancesByStatus", "Manager",new { statut = "APPROUVEE" })"><i class="fa fa-link"></i> <span>Approuvees</span></a></li>
        <li><a href="@Url.Action("AvancesByStatus", "Manager",new { statut = "REJETTEE" })"><i class="fa fa-link"></i> <span>Rejetees</span></a></li>
        <li><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Portefeuilles</span></a></li>
    </ul>
}
else if (Model.Utilisateur.Habilitation == "RESPONSABLE EXPLOITATION")
{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Menu De Navigation</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Consultation</span></a></li>
        <li><a href="@Url.Action("AvancesByStatus", "Manager",new { statut = "APPROUVEE" })"><i class="fa fa-link"></i> <span>Approuvees</span></a></li>
        <li><a href="@Url.Action("AvancesByStatus", "Manager",new { statut = "REJETTEE" })"><i class="fa fa-link"></i> <span>Rejetees</span></a></li>
    </ul>
}
else if (Model.Utilisateur.Habilitation == "DIRECTION" && !Model.Utilisateur.EstAdmin)
{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Menu De Navigation</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Consultation</span></a></li>
        <li><a href="@Url.Action("AvancesByStatus", "Manager",new { statut = "APPROUVEE" })"><i class="fa fa-link"></i> <span>Approuvees</span></a></li>
        <li><a href="@Url.Action("AvancesByStatus", "Manager",new { statut = "REJETTEE" })"><i class="fa fa-link"></i> <span>Rejetees</span></a></li>
        <li><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Portefeuilles</span></a></li>
    </ul>
}
else if (Model.Utilisateur.Habilitation == "DIRECTION" && Model.Utilisateur.EstAdmin)
{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">Menu De Navigation</li>
        <!-- Optionally, you can add icons to the links -->
        <li><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Consultation</span></a></li>
        <li><a href="@Url.Action("AvancesByStatus", "Manager",new { statut = "APPROUVEE" })"><i class="fa fa-link"></i> <span>Approuvees</span></a></li>
        <li><a href="@Url.Action("AvancesByStatus", "Manager",new { statut = "REJETTEE" })"><i class="fa fa-link"></i> <span>Rejetes</span></a></li>
        <li><a href="@Url.Action("Index", "Manager")"><i class="fa fa-link"></i> <span>Portefeuilles</span></a></li>
        <li class="treeview">
            <a href="@Url.Action("Index", "Manager")">
                <i class="fa fa-link"></i> <span>Gestion Acces</span>
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
            </a>
            <ul class="treeview-menu">
                <li><a href="@Url.Action("Index", "Manager")">Employes</a></li>
                <li><a href="@Url.Action("Index", "Manager")">Utilisateurs</a></li>
            </ul>
        </li>
    </ul>
}